apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: local-dev
spec:
  type: NodePort
  ports:
  - port: 5432
    targetPort: 5432
    nodePort: 30090
  selector:
    app: postgres