apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: local-dev
  name: airflow-scheduler-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list", "create", "delete"]