apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - jobs/init-pod-job.yaml
  - configmaps/configmap.yaml
  - services/postgres-service.yaml
  - services/webserver-service.yaml
  - roles/scheduler-role.yaml
  - rolebindings/scheduler-role-binding.yaml
  - deployments/webserver-deployment.yaml
  - deployments/scheduler-deployment.yaml
  - deployments/postgres-deployment.yaml